"""api_ref.py -- pick the few API-reference entries relevant to ONE spec and render them as a
compact Notes block for the coder prompt.

The entries themselves (signatures, one-line docs, import lines, verified facts) live in
b123d/api_ref.json, generated by INTROSPECTION of the installed build123d and the project
helper modules (scripts/gen_api_ref.py). This module only decides WHICH entries a spec
needs, from the spec's own words plus the code of the retrieved few-shots, so the token
cost stays small: a plain plate gets nothing, a filleted flange with a bolt circle gets
the edge-selection group and bolt_circle.

Called from cad_engine.inject_retrieval_notes, the one function every production-shaped
coder prompt goes through (harvest, fluid mode, the teacher/compile scripts, gemma
baseline) -- so train and serve prompts stay identical.
"""
from __future__ import annotations

import functools
import json
import re
from pathlib import Path

_JSON = Path(__file__).resolve().parent / "b123d" / "api_ref.json"

# (group name, spec regex, few-shot code regex or None, entry keys). A group fires when
# EITHER the spec text or any retrieved few-shot's code matches.
GROUPS = [
    ("edges",
     r"fillet|chamfer|round(?:ed|ing)?\s+(?:edge|corner)|blend|bevel",
     # spec-only: nearly every gold few-shot fillets something, so a code trigger here
     # fired on 670/673 specs (~430 tokens each) -- measured 2026-09-26, too broad.
     None,
     ["fillet", "chamfer", "ShapeList.filter_by", "ShapeList.group_by", "ShapeList.sort_by",
      "Edge.center", "Edge.start_point", "Vector"]),
    ("rotation",
     r"rotat|angled|\bangle\b|tilt|inclin|degree|°|slant|diagonal|oblique",
     r"\bRot(?:ation)?\(",
     ["Rotation", "Pos"]),
    ("profile",
     r"revolv|lathe|profile|loft|twist|sweep|extru|polyline|spline|saddle|curv|vase|"
     r"wav|sinus|helix|helical|cam\b|lobe|involute|taper",
     r"\brevolve\(|\bloft\(|\bextrude\(|\bmake_face\(|\bPolyline\(",
     ["extrude", "revolve", "loft", "make_face", "Polyline", "Plane"]),
    ("mirror", r"mirror|symmetric", r"\bmirror\(", ["mirror"]),
    ("cone", r"\bcone|conical|frustum|countersink|taper", r"\bCone\(", ["Cone"]),
    ("torus", r"torus|toroid|donut|doughnut", r"\bTorus\(", ["Torus"]),
    ("assembly", r"assembl|as two solids|separate (?:solids|parts|bodies)|\bpair of\b",
     r"\bCompound\(", ["Compound"]),
    ("bolt_circle",
     r"bolt[- ]circle|pitch circle|\bpcd\b|equally[- ]spaced|evenly[- ]spaced|"
     r"(?:holes?|bolts?) (?:on|around) (?:a|the) (?:\d+(?:\.\d+)?\s*mm\s*)?(?:diameter )?circle",
     r"\bbolt_circle\(", ["bolt_circle"]),
    ("cross_bore",
     r"cross[- ]?(?:bore|hole|drill)|radial|transverse|through the side|side (?:hole|bore)|"
     r"wrist[- ]pin|horizontal (?:hole|bore)|set[- ]?screw",
     r"\bcross_bore\(", ["cross_bore"]),
    ("counterbore", r"counter[- ]?bor|socket[- ]head", r"\bcounterbore_cutter\(",
     ["counterbore_cutter"]),
    ("countersink", r"counter[- ]?sink|countersunk|flat[- ]head", r"\bcountersink_cutter\(",
     ["countersink_cutter"]),
    ("gusset", r"gusset|\bbrace|stiffen|\brib\b|\bribs\b", r"\bgusset\(", ["gusset"]),
    ("ring_groove", r"groove|o-ring|circlip|snap[- ]ring|piston ring", r"\bring_groove\(",
     ["ring_groove"]),
    ("gear", r"\bgear\b|\bteeth\b|\bmodule\b", r"\bspur_gear\(", ["spur_gear"]),
    ("bolt", r"hex(?:agon)?[- ]?(?:head )?bolt|\bM\d+(?:\.\d+)?\b[^.]{0,30}\bbolt\b",
     r"\bhex_bolt\(", ["hex_bolt"]),
    ("section", r"i-beam|h-beam|\bw\d+x\d+|structural|universal (?:beam|column)",
     r"\bstructural_section\(", ["structural_section"]),
    ("thread", r"thread", r"\biso_thread\(", ["iso_thread"]),
    ("fastener", r"\bscrew\b|\bnut\b", r"\bscrew\(|\bnut\(", ["screw", "nut"]),
    ("bearing", r"ball[- ]bearing|\bbearing\b", r"\bball_bearing\(", ["ball_bearing"]),
]

HEADER = ("API REFERENCE -- exact signatures read from the installed build123d {ver} and the "
          "project helpers. Use these names, argument names and import lines exactly:")


@functools.lru_cache(maxsize=1)
def _load() -> dict:
    try:
        return json.loads(_JSON.read_text(encoding="utf-8"))
    except Exception:
        return {"entries": {}}


def select_keys(spec: str, fewshot_codes: list | tuple = ()) -> list:
    spec_l = (spec or "").lower()
    code = "\n".join(c for c in (fewshot_codes or []) if c)
    keys: list = []
    for _name, spec_re, code_re, entry_keys in GROUPS:
        if re.search(spec_re, spec_l, re.I) or (code and code_re and re.search(code_re, code)):
            for k in entry_keys:
                if k not in keys:
                    keys.append(k)
    return keys


def render(keys: list) -> str:
    data = _load()
    entries = data.get("entries", {})
    lines = []
    imports = []
    for k in keys:
        e = entries.get(k)
        if not e:
            continue
        line = f"  {e['sig']}  -- {e['doc']}"
        if e.get("fact"):
            line += f" NOTE: {e['fact']}"
        lines.append(line)
        if e.get("import"):
            imports.append(e["import"])
    if not lines:
        return ""
    out = HEADER.format(ver=data.get("build123d_version", "")) + "\n" + "\n".join(lines)
    if imports:
        out += "\n  Imports for the helpers above: " + "; ".join(imports)
    return out


def api_reference_note(spec: str, fewshot_codes: list | tuple = ()) -> str:
    """The Notes block for this spec, or "" when nothing relevant applies."""
    return render(select_keys(spec, fewshot_codes))
