"""warehouse.py — thin, hard-to-hallucinate factory helpers over gumyr/bd_warehouse.

bd_warehouse (the build123d author's own parametric part collection, MIT) provides
correct-by-construction mechanical parts: involute gears, ISO-standard fasteners, real
threads, bearings, pipe flanges. We expose a small, stable call surface so the local coder
*calls* a verified generator instead of hand-coding involute teeth or ISO thread helices
(which a 7B reliably gets wrong). Each function returns a build123d object usable directly in
algebra mode (`part - Cylinder(...)`, `Pos(...) * part`, etc.).

Like the b123d.domain helpers, anything produced here is trusted: the agent accepts it without
the visual critic, because the geometry is generated by a verified library, not freehanded.

Defaults favour a single clean solid (`simple=True` fasteners) so the deterministic gate's
"one fused solid" check holds; pass modelled_thread=True only when a real helical thread is
actually wanted (it produces a multi-solid thread body).
"""
from typing import Optional


def gear(module: float, teeth: int, thickness: float,
         pressure_angle: float = 20.0, bore: float = 0.0):
    """Involute spur gear, axis along Z, centred at the origin.
    Outside diameter = module*(teeth+2). `bore` (mm) cuts an optional central through-hole."""
    from bd_warehouse.gear import SpurGear
    from build123d import Cylinder
    g = SpurGear(module=module, tooth_count=teeth,
                 pressure_angle=pressure_angle, thickness=thickness)
    if bore and bore > 0:
        g = g - Cylinder(radius=bore / 2.0, height=thickness * 3)
    return g


_SCREW_KINDS = {
    "socket":     "SocketHeadCapScrew",
    "hex":        "HexHeadScrew",
    "countersunk":"CounterSunkScrew",
    "pan":        "PanHeadScrew",
    "button":     "ButtonHeadScrew",
    "cheese":     "CheeseHeadScrew",
    "set":        "SetScrew",
}

def screw(size: str = "M5-0.8", length: float = 20.0, head: str = "socket",
          modelled_thread: bool = False):
    """A standard metric screw. `size` like 'M3-0.5','M5-0.8','M8-1.25'. `head` is one of
    socket|hex|countersunk|pan|button|cheese|set. Axis along Z. modelled_thread=False (default)
    gives a clean single solid with a cosmetic thread; True models the real helical thread."""
    import bd_warehouse.fastener as F
    cls_name = _SCREW_KINDS.get(head.lower(), "SocketHeadCapScrew")
    cls = getattr(F, cls_name)
    return cls(size=size, length=length, simple=not modelled_thread)


def nut(size: str = "M5-0.8", modelled_thread: bool = False):
    """An ISO hex nut. `size` like 'M5-0.8'. Centred at the origin, axis along Z."""
    from bd_warehouse.fastener import HexNut
    return HexNut(size=size, simple=not modelled_thread)


def iso_thread(major_diameter: float, pitch: float, length: float, external: bool = True):
    """A real ISO 60° thread helix (external by default). Use to thread a custom shaft/bore;
    for standard fasteners prefer screw()/nut(). Returns a thread solid to fuse onto a core."""
    from bd_warehouse.thread import IsoThread
    return IsoThread(major_diameter=major_diameter, pitch=pitch,
                     length=length, external=external)


def ball_bearing(size: str = "M8-22-7"):
    """A single-row deep-groove ball bearing. `size` is 'bore-OD-width' in mm, e.g. 'M8-22-7'
    (8mm bore, 22mm OD, 7mm wide). Axis along Z, centred at the origin."""
    from bd_warehouse.bearing import SingleRowDeepGrooveBallBearing
    return SingleRowDeepGrooveBallBearing(size=size)


def pipe_flange(nps: str = "2", flange_class: int = 150):
    """An ASME B16.5 weld-neck pipe flange. `nps` nominal pipe size like '1','2','4';
    `flange_class` one of 150,300,600,900,1500,2500. Axis along Z."""
    from bd_warehouse.flange import WeldNeckFlange
    return WeldNeckFlange(nps=nps, flange_class=flange_class)
